#!/bin/bash

path=`./getcfg.sh base_dir`/`./getcfg.sh directory_name`

#start {remote_svr}
start()
{
	ssh $1 "cd $path && nohup ./main > nohup.out 2>&1 &"
}

stop()
{
	ssh $1 "killall -9 main"
}

#makedir {remote_svr}
makedir()
{
	ssh $1 "mkdir -p $path"
}

#deploy {remote_svr)
deploy()
{
	scp $path/* $1:$path
}

#main {function}
menu()
{
	#echo $1
	for svr in `cat iplist|grep -v '#'|uniq -i`
	do
		echo "[$svr]"
		case $1 in
			"1")
				start $svr
				;;
			"2")
				stop $svr
				;;
			"3")
				makedir $svr
				deploy $svr
				;;
		esac
	done
}

clear
printf "1.start\n2.stop\n3.deploy\n"
read -p "please input your choice:" a
menu $a
